name: Test urlargs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shell: [bash, sh, dash, zsh]
      fail-fast: false  # Continue with other shells even if one fails
    
    name: Test with ${{ matrix.shell }}
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install shells
      run: |
        sudo apt-get update
        sudo apt-get install -y zsh dash
    
    - name: Make script executable
      run: chmod +x urlargs tests/run_tests.sh tests/test_*.sh
    
    - name: Run tests with ${{ matrix.shell }}
      run: cd tests && ./run_tests.sh ${{ matrix.shell }}